# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('google_map', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=40)),
                ('rentperday', models.IntegerField(blank=True, default=0)),
                ('deposit', models.IntegerField(blank=True, default=0)),
                ('guests', models.IntegerField(blank=True, default=0)),
                ('house_type', models.CharField(choices=[('PG', 'PG'), ('HOUSE', 'HOUSE'), ('VILLA', 'VILLA'), ('FLAT', 'FLAT')], default='PG', max_length=10)),
                ('accom_type', models.CharField(choices=[('SHARED', 'SHARED'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=10)),
                ('accom_for', models.CharField(blank=True, max_length=20)),
                ('facilities', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'post',
            },
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postphotos', to='post.Post')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ShortlistedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('google_map', models.CharField(blank=True, max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'post_shortlistings',
            },
            bases=(models.Model, object),
        ),
    ]
