# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('google_map', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=40)),
                ('rentperday', models.IntegerField(blank=True, default=0)),
                ('facilities', models.CharField(blank=True, max_length=50)),
                ('avail_start_date', models.DateField(null=True)),
                ('avail_end_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'ordering': ('id',),
            },
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='PostAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('value', models.CharField(blank=True, max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='post.Post')),
            ],
            options={
                'db_table': 'post_attribute',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postphotos', to='post.Post')),
            ],
            options={
                'db_table': 'images',
                'ordering': ('id',),
            },
        ),
    ]
