# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlistedposts',
            name='post',
        ),
        migrations.RemoveField(
            model_name='shortlistedposts',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShortlistedPosts',
        ),
    ]
