# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='address2',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
