# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accom_for',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='accom_type',
            field=models.CharField(choices=[('SHARED', 'SHARED'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='deposit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='house_type',
            field=models.CharField(choices=[('PG', 'PG'), ('HOUSE', 'HOUSE'), ('VILLA', 'VILLA'), ('FLAT', 'FLAT')], default='PG', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='landmark',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
