# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160718_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guests',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
