# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postphotos', to='post.Post'),
        ),
        migrations.AlterModelTable(
            name='postphoto',
            table='images',
        ),
    ]
