# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160728_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattributes',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostAttributes',
        ),
    ]
