# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160619_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
