# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20160728_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('google_map', models.CharField(blank=True, max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_shortlistings',
                'ordering': ('id',),
            },
            bases=(models.Model, object),
        ),
    ]
