# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_shortlistedposts'),
        ('post', '0007_auto_20160801_0948'),
    ]

    operations = [
    ]
