# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'postbox',
            },
        ),
    ]
