# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbox',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postbox',
            name='phone',
            field=models.CharField(db_index=True,max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postbox',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postbox',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postbox',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
