# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=20)),
                ('address2', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('google_map', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('rentperday', models.IntegerField(blank=True, default=10)),
                ('keywords', models.CharField(blank=True, max_length=50)),
                ('facilities', models.CharField(blank=True, max_length=50)),
                ('avail_start_date', models.DateField(blank=True, null=True)),
                ('avail_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('progress', 'progress'), ('pending', 'pending'), ('verified', 'verified'), ('Rejected', 'rejected')], default='progress', max_length=1)),
                ('is_active', models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='F', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=20)),
                ('address2', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('google_map', models.CharField(blank=True, max_length=20)),
                ('emailid', models.EmailField(db_index=True, max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('phone_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_card_type', models.CharField(blank=True, max_length=20)),
                ('id_card_data', models.CharField(blank=True, max_length=20)),
                ('is_email_verified', models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='F', max_length=1)),
                ('is_phone_verified', models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='F', max_length=1)),
                ('is_id_verified', models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='F', max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
