# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160509_1146'),
        ('users', '0002_post_user'),
    ]

    operations = [
    ]
