# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('P', 'pending'), ('A', 'accepted'), ('R', 'rejected')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('filepath', models.CharField(blank=True, max_length=50)),
                ('filetype', models.CharField(blank=True, max_length=10)),
                ('size', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(blank=True, choices=[('P', 'pending'), ('A', 'accepted'), ('R', 'rejected')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'pending'), ('A', 'accepted'), ('R', 'rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='postattributes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='users.Post'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User'),
        ),
    ]
