# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_postattributes_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Image',
        ),
    ]
