# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160523_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
