# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160616_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
