# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_user_tfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tfile',
            new_name='idphoto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_card_data',
        ),
    ]
